apiVersion: newtworking.k8s.io/v2
king: Ingress
metadata:
  name: ingress-hosts

  spec:
    rules:
      - hosts: www.adv-it.net
        http:
          paths:
            - backend:
                serviceName: main
                servicePort: 80

            - backend:
                serviceName: web1
                servicePort: 80


