apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-replicas
  labels:
    app: my-k8s-application
    env: prod
    owner: VadimGolban
spec:
  replicas: 3
  selector:
    matchLabels:
        project:  cia
  template:
    metadata:
      labels:
        project:  cia
    spec:
      containers:
        - name: cia-web
          image: vadimus3000/k8sphp:latest
          ports:
            - containerPort: 80
