apiVersion: v1
kind: Service
metadata:
  name:  my-single2-pod-service
  labels:
    env    : prod
    owner  : VadimGolban
spec:
  selector:
    project: kgb     #Secevting PODS with those Labels
  ports:
    - name           : app2-listener
      protocol       : TCP
      port           : 80        #Port on LOad Balancer
      targetPort     : 80  #Port on POD
  type: LoadBalancer

